
-- KULLANDIÐIM DB
USE Northwind

-- BÜTÜN TABLOYU GETÝR
SELECT * FROM Employees

-- EMPLOYEES TABLOSUNDA EMPLOYEEID'YE GÖRE GETÝREN SORGU
SELECT
	E.EmployeeID,
	E.FirstName+' '+E.LastName 'AD SOYAD',
	E.Title AS ÜNVAN
FROM Employees E
WHERE E.EmployeeID=6

-- EMPLOYEES TABLOSUNDA ADI A ÝLE BAÞLAYANLAR
SELECT 
	*
FROM Employees
WHERE FirstName LIKE 'A%'

-- EMPLOYEES TABLOSUNDA ADI E ÝLE BÝTENLER
SELECT 
	*
FROM Employees
WHERE FirstName LIKE '%E'

-- PRODUCT TABLOSUNDA UNITPRICE 10 ÝLE 25 OLAN ÜRÜNLERÝN EN YÜKSEK UNITPRICE ÝLE SIRALAYAN SORGU
SELECT
	ProductName,
	UnitPrice
FROM Products
WHERE UnitPrice BETWEEN 10 AND 25
ORDER BY 2 DESC

-- PRODUCT OLARAK UNITSINSTOCK 50'DEN FAZLA OLAN 5 PRODUCTI GETÝR
SELECT TOP 5
	ProductName,
	UnitsInStock
FROM Products
WHERE UnitsInStock>50
ORDER BY 2 DESC
