
-- KULLANDIÐIM DB
USE Northwind

-- BÜTÜN TABLOYU GETÝR
SELECT * FROM Employees

-- EMPLOYEES TABLOSUNDA ADI A ÝLE BAÞLAYANLAR
SELECT 
	*
FROM Employees
WHERE FirstName LIKE 'A%'

-- EMPLOYEES TABLOSUNDA ADI E ÝLE BÝTENLER
SELECT 
	*
FROM Employees
WHERE FirstName LIKE '%E'